spring:
  application:
    name: nurijang

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  elasticsearch:
    uris: ${ELASTICSEARCH_HOST}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

cors:
  allowedOrigins: ${CORS_ALLOWED_ORIGINS}

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}