spring:
  application:
    name: nurijang

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  elasticsearch:
    uris: ${ELASTICSEARCH_HOST}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      api-url: ${OPENAI_API_URL}
      assistantId: ${OPENAI_ASSISTANT_ID}
