name: nurijang CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nurijang:latest
          platforms: linux/amd64

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            sudo su
            ACTIVE_SERVER=$(curl -fs http://localhost:8080/env | grep blue || echo "green")
            TARGET_SERVER="blue"
            TARGET_PORT=8080
            [ "$ACTIVE_SERVER" = "blue" ] && TARGET_SERVER="green" && TARGET_PORT=8081

            sudo docker stop nurijang-${TARGET_SERVER}-container || true
            sudo docker rm nurijang-${TARGET_SERVER}-container || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nurijang:latest
            sudo docker run -d --name nurijang-${TARGET_SERVER}-container --env-file .env -p ${TARGET_PORT}:${TARGET_PORT} ${{ secrets.DOCKER_USERNAME }}/nurijang:latest

            sudo ln -sf /etc/nginx/sites-available/${TARGET_SERVER} /etc/nginx/sites-enabled/nurijang
            sudo systemctl reload nginx

            sleep 10
            curl -f http://localhost:${TARGET_PORT}/env || exit 1