name: nurijang CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment values
        run: |
          rm -f .env 
          echo "${{ secrets.ENV }}" > .env
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nurijang:latest
          platforms: linux/amd64

      - name: SSH to EC2 and Deploy (Blue/Green)
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            sudo docker stop nurijang-blue-container || true
            sudo docker rm nurijang-blue-container || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nurijang:latest
            sudo docker run -d --name nurijang-blue-container --env-file .env -p 8080:8080 -e TZ=Asia/Seoul ${{ secrets.DOCKER_USERNAME }}/nurijang:latest

            curl -f https://your-domain.com/healthcheck || exit 1

            sudo docker stop nurijang-green-container || true
            sudo docker rm nurijang-green-container || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nurijang:latest
            sudo docker run -d --name nurijang-green-container --env-file .env -p 8080:8080 -e TZ=Asia/Seoul ${{ secrets.DOCKER_USERNAME }}/nurijang:latest

            sudo cp /etc/nginx/sites-available/green /etc/nginx/sites-enabled/nurijang
            sudo nginx -s reload

            sudo docker stop nurijang-blue-container || true
            sudo docker rm nurijang-blue-container || true
